# --------------------
# Define arguments.
# --------------------

# ==================== Alas ====================

Scheduler:
  Enable:
    type: checkbox
    value: false
    option: [ true, false ]
  NextRun: 2020-01-01 00:00:00
  Command: Alas
  ServerUpdate:
    value: 04:00
    display: hide
Emulator:
  Serial:
    value: auto
    valuetype: str
  GameClient:
    value: android
    option: [ android, cloud_android ]
  PackageName:
    value: auto
    option: [ auto, ]
  GameLanguage:
    value: auto
    option: [ auto, cn, en ]
  ScreenshotMethod:
    value: auto
    option: [
      auto,
      ADB,
      ADB_nc,
      uiautomator2,
      aScreenCap,
      aScreenCap_nc,
      DroidCast,
      DroidCast_raw,
      scrcpy,
      nemu_ipc,
      ldopengl,
    ]
  ControlMethod:
    value: MaaTouch
    option: [ minitouch, MaaTouch ]
  CloudPriorQueue: false
  AdbRestart: false
EmulatorInfo:
  Emulator:
    value: auto
    option: [
      auto,
      NoxPlayer,
      NoxPlayer64,
      BlueStacks4,
      BlueStacks5,
      BlueStacks4HyperV,
      BlueStacks5HyperV,
      LDPlayer3,
      LDPlayer4,
      LDPlayer9,
      MuMuPlayer,
      MuMuPlayerX,
      MuMuPlayer12,
      MEmuPlayer,
    ]
  name:
    value: null
    type: textarea
  path:
    value: null
    type: textarea
Error:
  Restart:
    value: game
    option: [ game, game_emulator ]
  SaveError: true
  ScreenshotLength: 1
  OnePushConfig:
    type: textarea
    mode: yaml
    value: 'provider: null'
Optimization:
  ScreenshotInterval: 0.3
  CombatScreenshotInterval: 1.0
  WhenTaskQueueEmpty:
    value: goto_main
    option: [ stay_there, goto_main, close_game ]

# ==================== Daily ====================

# Students' name will be filled in config updater
Invite:
  No1:
    value: yuuka
    option: [ ]
  No2:
    value: serika
    option: [ ]

CafeReward:
  ServerUpdate:
    value: True
    display: hide

Lesson:
  SchaleOffice: 1
  SchaleResidenceHall: 1
  Gehenna: 1
  Abydos: 1
  Millennium: 1
  Trinity: 1
  Red_winter: 1
  Hyakkiyako: 0
  DuShiratori: 0
  Shanhaijing: 0

Bounty:
  Overpass: 2
  DesertRailrode: 2
  Classroom: 2

Scrimmage:
  Trinity: 2
  Gehenna: 2
  Millennium: 2

TacticalChallenge:
  Counter:
    value: 0
    display: hide

Task:
  NewDay:
    value: True
    display: hide


# ==================== Dungeon ====================

Commission:
  BaseDefense: 1
  ItemRetrieval: 1

HardMission:
  Area: 19-3
  Time: 3

NormalMission:
  Area: 20-4
  Time: 1

# ==================== Event ====================

EventStory:
  AutoPass:
    type: checkbox
    value: false
    option: [ true, false ]
  State:
    value: True
    display: hide

EventQuest:
  Area: 9
  Time: 1
  AutoPass:
    type: checkbox
    value: false
    option: [ true, false ]
  State:
    value: True
    display: hide

# ==================== Tool ====================

Daemon:
  Enable:
    type: state
    value: true
    option: [ true ]
    option_bold: [ true, ]
  AimClicker:
    value: do_not_click
    option: [ item_enemy, item, enemy, do_not_click ]
PlannerScan:
  ResultAdd: false
