# --------------------
# Define default values
# --------------------

# ==================== Alas ====================


# ==================== Cafe ====================

Relationship:
  Scheduler:
    Enable: True
Invite:
  Scheduler:
    Enable: True
Earning:
  Scheduler:
    Enable: True

# ==================== Daily ====================

Lesson:
  Scheduler:
    Enable: True
Club:
  Scheduler:
    Enable: True
Crafting:
  Scheduler:
    Enable: True
HardMission:
  Scheduler:
    Enable: True
Bounty:
  Scheduler:
    Enable: True
Scrimmage:
  Scheduler:
    Enable: True
TacticalChallenge:
  Scheduler:
    Enable: True
Task:
  Scheduler:
    Enable: True
Mail:
  Scheduler:
    Enable: True
