# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Alas ====================

Alas:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Alas:
      - Emulator
      - EmulatorInfo
      - Error
      - Optimization
    Restart:
      - Scheduler

# ==================== Daily ====================

Daily:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Task:
      - Scheduler
    Lesson:
      - Scheduler
      - Lesson
    Club:
      - Scheduler
    HardMission:
      - Scheduler
      - HardMission
    Bounty:
      - Scheduler
      - Bounty
    Scrimmage:
      - Scheduler
      - Scrimmage
    TacticalChallenge:
      - Scheduler
    Event:
      - Scheduler
      - EventQuest
      - EventStory
    NormalMission:
      - Scheduler
      - NormalMission
    # Crafting:
    #   - Scheduler

# ==================== Reward ====================

Reward:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Earning:
      - Scheduler
    Club:
      - Scheduler
    Mail:
      - Scheduler
    Task:
      - Scheduler

# ==================== Cafe ====================

Cafe:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Earning:
      - Scheduler
    Invite:
      - Scheduler
      - Invite
    Relationship:
      - Scheduler

# ==================== Mission ====================

Mission:
  menu: 'collapse'
  page: 'setting'
  tasks:
    NormalMission:
      - Scheduler
      - NormalMission
    HardMission:
      - Scheduler
      - HardMission

# ==================== Event ====================

Event:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Event:
      - Scheduler
      - EventQuest
      - EventStory

# ==================== Dungeon ====================

Dungeon:
  menu: 'collapse'
  page: 'setting'
  tasks:
    Bounty:
      - Scheduler
      - Bounty
    Commission:
      - Scheduler
      - Commission
    Scrimmage:
      - Scheduler
      - Scrimmage


