# --------------------
# Define argument group of tasks.
# --------------------

# ==================== Alas ====================

Alas:
  menu: 'list'
  page: 'setting'
  tasks:
    Alas:
      - Emulator
      - EmulatorInfo
      - Error
      - Optimization
    Restart:
      - Scheduler

# ==================== Daily ====================

Daily:
  menu: 'list'
  page: 'setting'
  tasks:
    Cafe:
      - Scheduler
      - Invite
    Lesson:
      - Scheduler
      - Lesson
    Club:
      - Scheduler
    Crafting:
      - Scheduler
    HardMission:
      - Scheduler
      - HardMission
    Bounty:
      - Scheduler
      - Bounty
    Scrimmage:
      - Scheduler
      - Scrimmage
    TacticalChallenge:
      - Scheduler
    Task:
      - Scheduler
    Mail:
      - Scheduler

# ==================== Dungeon ====================

Dungeon:
  menu: 'list'
  page: 'setting'
  tasks:
    Commission:
      - Scheduler
      - Commission
    NormalMission:
      - Scheduler
      - NormalMission
    HardMission:
      - Scheduler
      - HardMission
    Event:
      - Scheduler
      - EventQuest
      - EventStory
    Crafting:
      - Scheduler

# ==================== Event ====================

Event:
  menu: 'list'
  page: 'setting'
  tasks:
    Event:
      - Scheduler
      - EventQuest
      - EventStory

# ==================== Tool ====================

Tool:
  menu: 'list'
  page: 'tool'
  tasks:
    Daemon:
      - Daemon
    PlannerScan:
      - PlannerScan
