import datetime

# This file was automatically generated by module/config/config_updater.py.
# Don't modify it manually.


class GeneratedConfig:
    """
    Auto generated configuration
    """

    # Group `Scheduler`
    Scheduler_Enable = False  # True, False
    Scheduler_NextRun = datetime.datetime(2020, 1, 1, 0, 0)
    Scheduler_Command = 'Alas'
    Scheduler_ServerUpdate = '04:00'

    # Group `Emulator`
    Emulator_Serial = 'auto'
    Emulator_GameClient = 'android'  # android, cloud_android
    Emulator_PackageName = 'auto'  # auto, BAtest
    Emulator_GameLanguage = 'auto'  # auto, cn, en
    Emulator_ScreenshotMethod = 'auto'  # auto, ADB, ADB_nc, uiautomator2, aScreenCap, aScreenCap_nc, DroidCast, DroidCast_raw, scrcpy, nemu_ipc, ldopengl
    Emulator_ControlMethod = 'MaaTouch'  # minitouch, MaaTouch
    Emulator_CloudPriorQueue = False
    Emulator_AdbRestart = False

    # Group `EmulatorInfo`
    EmulatorInfo_Emulator = 'auto'  # auto, NoxPlayer, NoxPlayer64, BlueStacks4, BlueStacks5, BlueStacks4HyperV, BlueStacks5HyperV, LDPlayer3, LDPlayer4, LDPlayer9, MuMuPlayer, MuMuPlayerX, MuMuPlayer12, MEmuPlayer
    EmulatorInfo_name = None
    EmulatorInfo_path = None

    # Group `Error`
    Error_Restart = 'game'  # game, game_emulator
    Error_SaveError = True
    Error_ScreenshotLength = 1
    Error_OnePushConfig = 'provider: null'

    # Group `Optimization`
    Optimization_ScreenshotInterval = 0.3
    Optimization_CombatScreenshotInterval = 1.0
    Optimization_WhenTaskQueueEmpty = 'goto_main'  # stay_there, goto_main, close_game

    # Group `Invite`
    Invite_No1 = 'yuuka'
    Invite_No2 = 'serika'

    # Group `CafeReward`
    CafeReward_ServerUpdate = True

    # Group `Lesson`
    Lesson_SchaleOffice = 1
    Lesson_SchaleResidenceHall = 1
    Lesson_Gehenna = 1
    Lesson_Abydos = 1
    Lesson_Millennium = 1
    Lesson_Trinity = 1
    Lesson_Red_winter = 1
    Lesson_Hyakkiyako = 0
    Lesson_DuShiratori = 0
    Lesson_Shanhaijing = 0

    # Group `Bounty`
    Bounty_Overpass = 2
    Bounty_DesertRailrode = 2
    Bounty_Classroom = 2

    # Group `Scrimmage`
    Scrimmage_Trinity = 2
    Scrimmage_Gehenna = 2
    Scrimmage_Millennium = 2

    # Group `TacticalChallenge`
    TacticalChallenge_Counter = 0

    # Group `Task`
    Task_NewDay = True

    # Group `Commission`
    Commission_BaseDefense = 1
    Commission_ItemRetrieval = 1

    # Group `HardMission`
    HardMission_Area = '19-3'
    HardMission_Time = 3

    # Group `NormalMission`
    NormalMission_Area = '20-4'
    NormalMission_Time = 1

    # Group `EventStory`
    EventStory_AutoPass = True  # True, False
    EventStory_State = True  # True, False

    # Group `EventQuest`
    EventQuest_Area = 9
    EventQuest_Time = 1
    EventQuest_AutoPass = True  # True, False
    EventQuest_State = True  # True, False

    # Group `Daemon`
    Daemon_Enable = True  # True
    Daemon_AimClicker = 'do_not_click'  # item_enemy, item, enemy, do_not_click

    # Group `PlannerScan`
    PlannerScan_ResultAdd = False
